#!/bin/bash

sudo apt update
sudo apt install software-properties-common ca-certificates lsb-release apt-transport-https
LC_ALL=C.UTF-8 sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install -y php8.2 php8.2-mysql php8.2-mbstring php8.2-xml php8.2-curl
sudo apt install -y mysql-client

# add alias for php8.2
echo "alias php='php8.2'" >> ~/.bash_aliases 
# reset aliases for the current session
source ~/.bash_aliases
# reset all bash sessions
exec bash